### ISSUE TITLE
Model definition not included when response definition has an external $ref containing a schema $ref

### ISSUE THREAD

**Issue by BertrandGouny** [go-swagger/go-swagger#1429]
## Problem statement
Not sure how to say that in a simple way, the example may be more relevant :) 
Model definition is not included when a response definition has an external $ref containing a schema with $ref.

With `swagger flatten` the model definition is missing, 
`swagger validate` throw this error : 
```
some references could not be resolved in spec. First found: object has no key "Error"
```
## Steps to reproduce
**responses.yaml:**
```
swagger: '2.0'
info:
  title: Responses
  version: 0.1.0
definitions:
  Error:
    type: object
    description: |
      Contains all the properties any error response from the API will contain.
      Some properties are optional so might be empty most of the time
    required:
      - code
      - message
    properties:
      code:
        description: the error code, this is not necessarily the http status code
        type: integer
        format: int32
      message:
        description: a human readable version of the error
        type: string
      helpUrl:
        description: an optional url for getting more help about this error
        type: string
        format: uri

responses:
  BadRequest:
    description: Bad request
    schema:
      $ref: '#/definitions/Error'

paths:
  /:
    get:
      summary: GET
      operationId: getAll
      responses:
        200:
          description: Ok
```
**swagger.yaml**
```
swagger: '2.0'
info:
  title: Object
  version: 0.1.0

paths:
  /:
    get:
      summary: GET
      operationId: getAll
      responses:
        200:
          description: Ok
        400:
          $ref: './responses.yaml#/responses/BadRequest'
```

**Commands**
```
swagger validate swagger.yaml
swagger flatten swagger.yaml
```

## Environment
swagger version: dev + latest commit of github.com/go-openapi/validate

**Comment by gregmarr** [comment]
Just guessing that the `$ref` isn't being resolved in the right file.  Does it work if you reference `./responses.yaml#/definitions/Error`?  (Not that I think you should do this in the end, just guessing about the cause.)

**Comment by BertrandGouny** [comment]
Yes it work by setting `./responses.yaml#/definitions/Error` in the responses.yaml file.
Will use this workaround thanks :)

**Comment by fredbi** [comment]
Could reproduce this and the work around as well, but could not find a fix right away.
Again a failure with $refs...
Opened a dedicated issue for that in go-openapi/spec#65

**Comment by casualjim** [comment]
have you tried running flatten before generating?

**Comment by fredbi** [comment]
@casualjim  It seems he has. I tested this directly with spec and this $ref is not resolved at all, unless you explicit the filename (in its own file!), as suggested @gregmarr

**Comment by BertrandGouny** [comment]
@casualjim yes, with swagger flatten the model definition is missing, but no error is thrown. 

@fredbi thanks for the review, i tried to find a fix too but this is too complicated to me :s

**Comment by fredbi** [comment]
@BertrandGouny  go-openapi/spec#70 should solve your issue.

**Comment by fredbi** [comment]
Salut Bertrand.

You should either update vendor, or if just for temporary testing setup, temporarily rename vendor/github.com/go-openapi to another name and rebuild swagger.

Please pull the latest spec master, since another patch on this has been released.

I also had problems when testing validate with the testcase I added from your initial input, but not a panic

**Comment by Freyert** [comment]
@fredbi I pulled `master` and did the following:

```
go get -u github.com/go-swagger/go-swagger/cmd/swagger
go install github.com/go-swagger/go-swagger/cmd/swagger
./bin/swagger validate file.yaml

2018/04/11 13:53:51
The swagger spec at "/Users/fultonbyrne/Desktop/photic-docs/_data/networkmanager_swagger.yaml" showed up some valid but possiby unwanted constructs.
2018/04/11 13:53:51 See warnings below:
2018/04/11 13:53:51 - WARNING: parameter "#/parameters/includeChildren" is not used anywhere

The swagger spec at "/Users/fultonbyrne/Desktop/photic-docs/_data/networkmanager_swagger.yaml" is invalid against swagger specification 2.0.
See errors below:
- some references could not be resolved in spec. First found: object has no key "Release"
```

**Comment by fredbi** [comment]
The spec is more important than the gopkg.toml, unless you want me to check every single commit number in your attachment?

**Comment by Freyert** [comment]
Let me get to minimal viable. There's nothing really special that we're doing. It's just that the refs point to items within the same document.

**Comment by fredbi** [comment]
What is the TL,DR of your gopkg? you got an updated spec and validate compared to the go-swagger vendor in go-swagger?

**Comment by Freyert** [comment]
Yup, I've updated to use all the latest versions so I _believe_ and yet it still can't resolve `$refs` that point within the file via `#/definitions/Model`.

**Comment by fredbi** [comment]
I assume it has something to do with transitive $ref ($ref pointing to another file then another $ref in the same file). Correct in your case?

**Comment by Freyert** [comment]
So, no his workaround does not work in this case. The `$ref` points to 
"./networkmanager_swagger.yaml/#/definitions/Membership" which _is in the same file_ to begin with.

**Comment by gregmarr** [comment]
So the root yaml file has references to itself that include the filename?  That's a bit odd.  The case where I suggested adding that before was for when the reference was in a different file referenced from the root, and I was only suggesting that as a test, not a permanent fix.  I would not expect a reference to a definition in the same file to be qualified with the filename.

**Comment by fredbi** [comment]
Thank you Greg. I was just suggesting this to help pinpointing the actual issue.

**Comment by Freyert** [comment]
After trying to achieve a minimal reproducible I've identified that there's something amiss with our definition. I'll keep working with it to see if I can isolate the issue. Thank you all for your help!

I've really loved this tool so far. It's gotten me farther than any other swagger tool I've used yet. The validator is incredibly helpful most of the time. Thank you all for your work!

**Comment by BertrandGouny** [comment]
Any update on this ? the fix seems to not solve the issue example

**Comment by fredbi** [comment]
I could narrow the issue and prepare a more general testcase.
However, the fix is not obvious.

The problem lies in spec expandResponse() and expandParameter() when the SkipSchema=true option is used (which is what the flatten command uses).

With this option, remote $ref's on the response (or parameter) object are properly expanded, but the content of their schema is left unchanged. So any $ref which is in the remote schema is not relocated to the new root after expansion (or even expanded).

This does not happen when SkipSchema=false, because all $ref's are properly processed.

These functions should in my opinion be updated to expand remote $ref (and only those) in the schema, even though the skipSchema flag is set.
