### ISSUE TITLE
Code gen: undefined: swag in swag.IsZero

### ISSUE THREAD

**Issue by kyteague** [go-swagger/go-swagger#656]
## Problem statement

I get multiple errors when I try to build with the latest version of swagger (0.6.0).  This is the first of many.  It seems that the generated code is missing imports.
## Swagger specification

```
swagger: "2.0"
info:
  version: 1.0.0
  title: OnFrontiers API
host: api.onfrontiers.com
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /experts:
    get:
      summary: List all experts
      operationId: listExperts
      tags:
        - experts
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          type: integer
          format: int32
      responses:
        "200":
          description: An paged array of users
          headers:
            x-next:
              type: string
              description: A link to the next page of responses
          schema:
            $ref: '#/definitions/User'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /users/{userId}:
    get:
      summary: Info for a specific user
      operationId: showUserById
      tags:
        - users
      parameters:
        - name: userId
          in: path
          required: true
          description: The id of the user to retrieve
          type: string
      responses:
        "200":
          description: Expected response to a valid request
          schema:
            $ref: '#/definitions/Users'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  User:
    required:
      - id
      - name
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      tag:
        type: string
  Users:
    type: array
    items:
      $ref: '#/definitions/User'
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string

```
## Steps to reproduce

```
$ swagger generate server -f swagger.yml
$ go build <repo path>/cmd/on-frontiers-server
```

**Comment by casualjim** [comment]
did you do a `go get -u github.com/go-openapi/runtime` ?

**Comment by daved** [comment]
Don't forget to also re-generate the relevant output (`swagger generate {args...}`) after running `go get -u github.com/go-openapi/runtime`.

**Comment by linearregression** [comment]
@daved   Does not seem to work for me. Still getting swag.IsZero undefined.

**Comment by casualjim** [comment]
the latest version of swagger tells you which dependencies you have to vendor.
But can you share your spec so I can try it in a docker container. The error message is a bit vague like this and that makes it hard to troubleshoot

**Comment by casualjim** [comment]
@kyteague is this still an issue for you?
From version 0.7.0 we print the dependencies you require

**Comment by Rio** [comment]
For me this is still a problem.

I'm starting out with an empty `$GOPATH` and a the swagger `0.7.4` binary.
Following the simple server tutorial I generate the `swagger.yml` with:

```
swagger init spec \
  --title "A To Do list application" \
  --description "The product of a tutorial on goswagger.io" \
  --version 1.0.0 \
  --scheme http \
  --consumes application/io.goswagger.examples.todo-list.v1+json \
  --produces application/io.goswagger.examples.todo-list.v1+json
```

Which finishes with the message:

```
For this generation to compile you need to have some packages in your GOPATH:

  * github.com/go-openapi/runtime
  * github.com/tylerb/graceful
  * github.com/jessevdk/go-flags
  * golang.org/x/net/context
```
I `go get -u` those and add a simple hello world get handler that returns a string and 200 to the swagger spec. Then I try to build the server with `go build -v cmd/a-to-do-list-application-server/main.go`.
It failes on missing packages:
- `github.com/go-openapi/analysis`
- `github.com/go-openapi/loads`
- `github.com/go-openapi/spec`
- `github.com/go-openapi/validate`
- `github.com/gorilla/context`

After installing those I try to compile again and finally get the message this issue is built on:

```bash
[rio@ravage testserver]$ go build -v cmd/a-to-do-list-application-server/main.go 
github.com/go-openapi/runtime/middleware/denco
github.com/go-openapi/runtime/middleware/header
github.com/go-openapi/runtime/middleware/untyped
github.com/go-openapi/runtime/security
github.com/go-openapi/runtime/middleware
testserver/restapi/operations
# testserver/restapi/operations
restapi/operations/a_to_do_list_application_api.go:57: undefined: swag in swag.CommandLineOptionsGroup
```

Running `swagger generate server --spec swagger.yml` again will fix this with this diff:

```diff
diff --git a/restapi/operations/a_to_do_list_application_api.go b/restapi/operations/a_to_do_list_application_api.go
index 19060b2..e7942cc 100644
--- a/restapi/operations/a_to_do_list_application_api.go
+++ b/restapi/operations/a_to_do_list_application_api.go
@@ -13,6 +13,7 @@ import (
        middleware "github.com/go-openapi/runtime/middleware"
        spec "github.com/go-openapi/spec"
        strfmt "github.com/go-openapi/strfmt"
+       "github.com/go-openapi/swag"
 )
 
 // NewAToDoListApplicationAPI creates a new AToDoListApplication instance
diff --git a/restapi/operations/get_parameters.go b/restapi/operations/get_parameters.go
index 8524a0c..941e437 100644
--- a/restapi/operations/get_parameters.go
+++ b/restapi/operations/get_parameters.go
@@ -7,6 +7,7 @@ import (
        "net/http"
 
        "github.com/go-openapi/errors"
+       "github.com/go-openapi/runtime/middleware"
 )
 
 // NewGetParams creates a new GetParams object
diff --git a/restapi/server.go b/restapi/server.go
index 1a23589..a92af06 100644
--- a/restapi/server.go
+++ b/restapi/server.go
@@ -10,6 +10,7 @@ import (
        "sync"
        "time"
 
+       "github.com/go-openapi/swag"
        flags "github.com/jessevdk/go-flags"
        graceful "github.com/tylerb/graceful"
```

So it does seem the swag  and middleware import is not coming through on first generation.
Also the first generation message is missing some packages.

**Comment by GlenDC** [comment]
@Rio this seems to be recently fixed via https://github.com/go-swagger/go-swagger/pull/867 and possible others. Could you please confirm?

I tested it myself using your reproduce steps, and it works for me, once I get all the dependencies via go get.

Note: the `For this generation to compile you need to have some packages in your GOPATH` is incorrect, as I also had to `go get` the following packages: `github.com/docker/go-units github.com/go-openapi/analysis github.com/go-openapi/loads github.com/go-openapi/spec github.com/go-openapi/validate github.com/gorilla/context`

**Comment by gregmarr** [comment]
I think if you start with `github.com/go-openapi/validate` it gets the rest of the ones that you need.

**Comment by gregmarr** [comment]
I remember talking to @casualjim about this, and if I remember correctly, he was surprised that `go-openapi/runtime` didn't pull in `go-openapi/validate`.

**Comment by casualjim** [comment]
I was able to reproduce that with glide, gvt otoh does everything as I expect

related: #818

**Comment by Rio** [comment]
it's not solved for me. I still need to do another `swagger generate` to get the proper imports set. I've even got one extra that's missing:
